<?php $this->headStyle()->appendStyle('.inputs label { display: block; }'); ?>

<?php $form->prepare(); ?>

<?php
    echo $this->translate('"Archive Repertory" plugin allows to save files in a hierarchical structure and to keep original name of files.') . '<br />';
    echo sprintf($this->translate('See %s for more information.'), '<a href="https://github.com/Daniel-KM/ArchiveRepertory">ReadMe</a>') . '<br />';
    echo '<br />';
    echo $this->translate('When all options are set, files will be saved in "files / original / item_identifier / original_filename.ext" instead of "files / original / hashed_filename.ext".') . '<br />';
    echo '<p><strong>' . $this->translate('Warning') . '</strong></p>';
    echo '<ul>';
    echo '<li>' . $this->translate('Currently, changes in these settings affect only new uploaded files. So, after a change, old files will continue to be stored and available as previously.') . '</li>';
    echo '<li>' . $this->translate('Nevertheless, when an item is updated, attached files will follow the current settings, so all files of a record will move and stay together inside the same folder.') . '</li>';
    echo '<li>' . $this->translate('Currently, no check is done on the name of folders, either for items. No files will be lost if two folders have the same name, but files attached to a record will be mixed in this folder.') . '</li>';
    echo '</ul>';
    echo sprintf($this->translate('Omeka works fine with filenames with Unicode characters ("é", "ñ", "Å"...). In case of issues, see %s.'), '<a href="https://github.com/Daniel-KM/ArchiveRepertory">ReadMe</a>');
    echo ' ' . $this->translate('If this is not the case, filenames should use only Ascii characters.') . '<br />';
    $allow_unicode = $this->checkUnicodeInstallation();
    if (empty($allow_unicode)) {
        echo '<p>' . $this->translate('This server is compatible with Unicode.') . '</p>';
    }
    else {
        echo '<p><strong>' . $this->translate('Warning') . '</strong></p>';
        echo $this->translate('This server is not fully compatible with Unicode:') . '<br />';
        echo '<ul>';
        if (isset($allow_unicode['ascii'])) {
            echo '<li>' . $allow_unicode['ascii'] . '<br/>';
            echo ' ' . $this->translate('Use only an Ascii character as first character of your filenames or set the option "Convert first character of filename".') . '</li>';
        }
        if (isset($allow_unicode['cli'])) {
            echo '<li>' . $allow_unicode['cli'] . '<br/>';
            echo $this->translate('Usually, this is not a problem with this plugin and common plugins.');
            echo ' ' . $this->translate('But if you use a plugin that calls a program via the command line of the server, filenames issues can occur.') .'</li>';
        }
        if (isset($allow_unicode['fs'])) {
            echo '<li>' . $allow_unicode['fs'] . '<br/>';
            echo $this->translate('It is strongly recommanded to convert your filename to ascii.') . '</li>';
        }
        echo '</ul>';
    }
?>

<fieldset id="fieldset-items">
    <legend><?php echo $this->translate('Items'); ?></legend>

    <?php echo $this->formRow($form->get('archive_repertory_item_folder')); ?>
    <div id="item-prefix-convert-wrapper">
        <?php echo $this->formRow($form->get('archive_repertory_item_prefix')); ?>
        <?php echo $this->formRow($form->get('archive_repertory_item_convert')); ?>
    </div>
</fieldset>

<fieldset id="fieldset-files">
    <legend><?php echo $this->translate('Files'); ?></legend>

    <?php echo $this->formRow($form->get('archive_repertory_file_keep_original_name')); ?>
</fieldset>

<fieldset id="fieldset-derivative-folders">
    <legend><?php echo $this->translate('Special derivative folders'); ?></legend>

    <?php echo $this->formRow($form->get('archive_repertory_derivative_folders')); ?>
</fieldset>

<script type="text/javascript">
(function($) {
    var itemPrefixConvertWrapper = $("#item-prefix-convert-wrapper");
    jQuery(document).ready(function () {
        $('#archive_repertory_item_folder').on('click', function() {
            if (this.value === '' || this.value === 'id') {
                itemPrefixConvertWrapper.hide();
            } else {
                itemPrefixConvertWrapper.show();
            }
        }).trigger('click');
    });
})(jQuery);
</script>
