<?php

$form->prepare();
 echo $this->form()->openTag($form);
 ?>

<?php

    echo $this->translate('"Archive Repertory" plugin allows to save files in a hierarchical structure and to keep original name of files.') . '<br />';
    echo sprintf($this->translate('See %s for more information.'), '<a href="https://github.com/Daniel-KM/ArchiveRepertory">ReadMe</a>') . '<br />';
    echo '<br />';
    echo $this->translate('When all options are set, files will be saved in "files / original / item_identifier / original_filename.ext" instead of "files / original / hashed_filename.ext".') . '<br />';
    echo '<p><strong>' . $this->translate('Warning') . '</strong></p>';
    echo '<ul>';
    echo '<li>' . $this->translate('Currently, changes in these settings affect only new uploaded files. So, after a change, old files will continue to be stored and available as previously.') . '</li>';
    echo '<li>' . $this->translate('Nevertheless, when an item is updated, attached files will follow the current settings, so all files of a record will move and stay together inside the same folder.') . '</li>';
    echo '<li>' . $this->translate('Currently, no check is done on the name of folders, either for items. No files will be lost if two folders have the same name, but files attached to a record will be mixed in this folder.') . '</li>';
    echo '</ul>';
    echo sprintf($this->translate('Omeka works fine with filenames with Unicode characters ("é", "ñ", "Å"...). In case of issues, see %s.'), '<a href="https://github.com/Daniel-KM/ArchiveRepertory">ReadMe</a>');
    echo ' ' . $this->translate('If this is not the case, filenames should use only Ascii characters.') . '<br />';
    $allow_unicode = checkUnicodeInstallation();
    if (empty($allow_unicode)) {
        echo '<p>' . $this->translate('This server is compatible with Unicode.') . '</p>';
    }
    else {
        echo '<p><strong>' . $this->translate('Warning') . '</strong></p>';
        echo $this->translate('This server is not fully compatible with Unicode:') . '<br />';
        echo '<ul>';
        if (isset($allow_unicode['ascii'])) {
            echo '<li>' . $allow_unicode['ascii'] . '<br/>';
            echo ' ' . $this->translate('Use only an Ascii character as first character of your filenames or set the option "Convert first character of filename".') . '</li>';
        }
        if (isset($allow_unicode['cli'])) {
            echo '<li>' . $allow_unicode['cli'] . '<br/>';
            echo $this->translate('Usually, this is not a problem with this plugin and common plugins.');
            echo ' ' . $this->translate('But if you use a plugin that calls a program via the command line of the server, filenames issues can occur.') .'</li>';
        }
        if (isset($allow_unicode['fs'])) {
            echo '<li>' . $allow_unicode['fs'] . '<br/>';
            echo $this->translate('It is strongly recommanded to convert your filename to ascii.') . '</li>';
        }
        echo '</ul>';
    }
?>

<fieldset id="fieldset-items"><legend><?php echo $this->translate('Items'); ?></legend>
<?php echo $this->formRow($form->get('archive_repertory_item_folder')); ?>

<?php echo $this->formRow($form->get('archive_repertory_item_prefix')); ?>

<?php echo $this->formRow($form->get('archive_repertory_item_convert')); ?>

</fieldset>
<fieldset id="fieldset-files"><legend><?php echo $this->translate('Files'); ?></legend>

<?php echo $this->formRow($form->get('archive_repertory_file_keep_original_name'));
      echo $this->formRow($form->get('archive_repertory_file_convert'));
//      echo $this->formRow($form->get('archive_repertory_file_base_original_name'));
 ?>


</fieldset>

<fieldset id="fieldset-max-download"><legend><?php echo $this->translate('Others'); ?></legend>
<?php //echo $this->formRow($form->get('archive_repertory_download_max_free_download')); 
?>

  <div class='input-block'>
    <?php $this->ckEditor(); ?>
    <?php  echo $this->formRow($form->get('archive_repertory_legal_text'));

    ?>
    <script type='text/javascript'>
     $('#archive_repertory_legal_text').ckeditor();
    </script>
  </div>
</fieldset>
<?php echo $this->form()->closeTag(); ?>

<script type="text/javascript">

    var dropItem = document.getElementById("archive_repertory_item_folder");
    var fieldItemPrefix = document.getElementById("item-prefix");
    var fieldItemAscii = document.getElementById("item-ascii");
    dropItem.onclick = function() {
        if (dropItem.value == "none" || dropItem.value == "id"){
            fieldItemPrefix.style.display = "none";
            fieldItemAscii.style.display = "none";
        } else {
            fieldItemPrefix.style.display = "block";
            fieldItemAscii.style.display = "block";
        }
    }

    jQuery(document).ready(function () {
        dropItem.onclick();
    });
    jQuery(window).load(function () {
      Omeka.wysiwyg({
        mode: 'specific_textareas',
        editor_selector: 'html-editor'
      });
    });
</script>
